# Standart server settings
server:
 host: "127.0.0.1"
 port: "8081"
 protocol: "tcp"
 debug: false


# List of databases included in the work
dbList:
 MySqlActive: false
 PostgresActive: true
 ClickHouseActive: true
 MongoDBActive: false
 SnowFalkeActive: false
 TimeScaleActive: false